language: python
python:
  - "3.6"

env:
  - PLATFORMIO_PROJECT_DIR=examples/arduino-fade-all-pins
  - PLATFORMIO_PROJECT_DIR=examples/arduino-internal-lib
  - PLATFORMIO_PROJECT_DIR=examples/arduino-ping-hc04
  - PLATFORMIO_PROJECT_DIR=examples/spl-blink
  - PLATFORMIO_PROJECT_DIR=examples/spl-flash
  - PLATFORMIO_PROJECT_DIR=examples/spl-uart

install:
  - pip install -U https://github.com/platformio/platformio/archive/develop.zip
  - platformio platform install file://.

script:
  - platformio run -d $PLATFORMIO_PROJECT_DIR

notifications:
  email: false
