language: python
python:
  - "3.7"

env:
  - PLATFORMIO_PROJECT_DIR=examples/arduino-fade-all-pins
  - PLATFORMIO_PROJECT_DIR=examples/arduino-internal-lib
  - PLATFORMIO_PROJECT_DIR=examples/arduino-ping-hc04
  - PLATFORMIO_PROJECT_DIR=examples/spl-blink
  - PLATFORMIO_PROJECT_DIR=examples/spl-flash
  - PLATFORMIO_PROJECT_DIR=examples/spl-uart
  - PLATFORMIO_PROJECT_DIR=examples/reg-blinker
  - PLATFORMIO_PROJECT_DIR=examples/reg-timer
  - PLATFORMIO_PROJECT_DIR=examples/reg-uart

install:
  - pip install -U https://github.com/OS-Q/S03/archive/master.zip
  - platformio platform install file://.

script:
  - platformio run -d $PLATFORMIO_PROJECT_DIR

notifications:
  email: false
