build: off
environment:

  matrix:
    - PLATFORMIO_PROJECT_DIR: "examples/arduino-fade-all-pins"
    - PLATFORMIO_PROJECT_DIR: "examples/arduino-internal-lib"
    - PLATFORMIO_PROJECT_DIR: "examples/arduino-ping-hc04"
    - PLATFORMIO_PROJECT_DIR: "examples/spl-blink"
    - PLATFORMIO_PROJECT_DIR: "examples/spl-flash"
    - PLATFORMIO_PROJECT_DIR: "examples/spl-uart"

install:
  - cmd: git submodule update --init --recursive
  - cmd: SET PATH=C:\Python36\Scripts;%PATH%
  - cmd: pip3 install -U https://github.com/platformio/platformio/archive/develop.zip
  - cmd: platformio platform install file://.

test_script:
  - cmd: platformio run -d %PLATFORMIO_PROJECT_DIR%

# notifications:
#   - provider: Slack
#     incoming_webhook:
#       secure: 
#     on_build_success: false
#     on_build_failure: true
#     on_build_status_changed: true
